name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "dk-dl.zhangkai.xin", custom_domain = true },
  { pattern = "dk-dl.zhangkaixin.cc", custom_domain = true },
  { pattern = "dk-dl.zhangkaix.ink", custom_domain = true },
  { pattern = "dk-dl.cartonbox.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
routes = [
  { pattern = "dk-dls.zhangkai.xin", custom_domain = true },
  { pattern = "dk-dls.zhangkaixin.cc", custom_domain = true },
  { pattern = "dk-dls.zhangkaix.ink", custom_domain = true },
  { pattern = "dk-dls.cartonbox.top", custom_domain = true },
]

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
